# Commands
###
POST http://localhost:8000/api/v1/openBankAccount
Content-Type: application/json

{
  "accountHolder": "John Done",
  "accountNumber": "123456789",
  "accountType": "SAVINGS",
  "initialBalance": 50.0
}

###
POST http://localhost:8000/api/v1/openBankAccount
Content-Type: application/json

{
  "accountHolder": "Ivo Woltring",
  "accountNumber": "987654321",
  "accountType": "SAVINGS",
  "initialBalance": 42.0
}

###
POST http://localhost:8000/api/v1/openBankAccount
Content-Type: application/json

{
  "accountHolder": "Jane Doe",
  "accountNumber": "4242424242",
  "accountType": "SAVINGS",
  "initialBalance": 42.0
}

###
PUT http://localhost:8000/api/v1/depositFunds/{{id}}
Content-Type: application/json

{
  "amount": 0.99
}


###
PUT http://localhost:8000/api/v1/withdrawFunds/{{id}}
Content-Type: application/json

{
  "amount": 0.93
}

###
DELETE http://localhost:8000/api/v1/closeAccount/{{id}}


###
POST http://localhost:8000/api/v1/restoreReadDatabase

# Queries
###
GET http://localhost:8001/api/v1/bankAccountLookup
Accept: application/json

###
GET http://localhost:8001/api/v1/bankAccountLookup/byId/{{id}}
Accept: application/json

###
GET http://localhost:8001/api/v1/bankAccountLookup/byAccountHolder/John Doe
Accept: application/json

###
GET http://localhost:8001/api/v1/bankAccountLookup/withBalance/GREATER_THAN/50
Accept: application/json

###
GET http://localhost:8001/api/v1/bankAccountLookup/withBalance/LESS_THAN/100
Accept: application/json

###
GET http://localhost:8001/api/v1/bankAccountLookup/withBalance/BETWEEN/50/100