# Commands
###
POST http://localhost:8000/api/v1/openBankAccount
Content-Type: application/json

{
  "accountHolder": "John Doe",
  "accountNumber": "123456789",
  "accountType": "SAVINGS",
  "initialBalance": 50.0
}

###
POST http://localhost:8000/api/v1/openBankAccount
Content-Type: application/json

{
  "accountHolder": "Ivo woltring",
  "accountNumber": "987654321",
  "accountType": "SAVINGS",
  "initialBalance": 42.0
}

###
PUT http://localhost:8000/api/v1/depositFunds/cbf80afe-4d1b-4574-8814-d51cf624c158
Content-Type: application/json

{
  "amount": 100.0
}


###
PUT http://localhost:8000/api/v1/withdrawFunds/cbf80afe-4d1b-4574-8814-d51cf624c158
Content-Type: application/json

{
  "amount": 42.0
}

###
DELETE http://localhost:8000/api/v1/closeAccount/cbf80afe-4d1b-4574-8814-d51cf624c158


###
POST http://localhost:8000/api/v1/restoreReadDatabase

# Queries
###
GET http://localhost:8001/api/v1/bankAccountLookup
Accept: application/json

###
GET http://localhost:8001/api/v1/bankAccountLookup/byId/cbf80afe-4d1b-4574-8814-d51cf624c158
Accept: application/json

###
GET http://localhost:8001/api/v1/bankAccountLookup/byAccountHolder/John Doe
Accept: application/json

###
GET http://localhost:8001/api/v1/bankAccountLookup/withBalance/GREATER_THAN/50
Accept: application/json

###
GET http://localhost:8001/api/v1/bankAccountLookup/withBalance/LESS_THAN/100
Accept: application/json