# Commands
###
POST http://localhost:8000/api/v1/openBankAccount
Content-Type: application/json

{
  "accountHolder": "John Doe",
  "accountNumber": "123456789",
  "accountType": "SAVINGS",
  "initialBalance": 50.0
}

###
POST http://localhost:8000/api/v1/openBankAccount
Content-Type: application/json

{
  "accountHolder": "Ivo Wolf",
  "accountNumber": "987654321",
  "accountType": "SAVINGS",
  "initialBalance": 42.0
}

###
PUT http://localhost:8000/api/v1/depositFunds/d9bc3ebf-8665-4d13-9529-161f50a43e7c
Content-Type: application/json

{
  "amount": 50.0
}


###
PUT http://localhost:8000/api/v1/withdrawFunds/d9bc3ebf-8665-4d13-9529-161f50a43e7c
Content-Type: application/json

{
  "amount": 42.0
}

###
DELETE http://localhost:8000/api/v1/closeAccount/d9bc3ebf-8665-4d13-9529-161f50a43e7c


# Queries
###
GET http://localhost:8001/api/v1/bankAccountLookup
Accept: application/json

###
GET http://localhost:8001/api/v1/bankAccountLookup/byId/d9bc3ebf-8665-4d13-9529-161f50a43e7c
Accept: application/json

###
GET http://localhost:8001/api/v1/bankAccountLookup/byAccountHolder/John Doe
Accept: application/json

###
GET http://localhost:8001/api/v1/bankAccountLookup/withBalance/GREATER_THAN/50
Accept: application/json

###
GET http://localhost:8001/api/v1/bankAccountLookup/withBalance/LESS_THAN/100
Accept: application/json