server:
  port: 8001

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/accounting
    username: accounting
    password: s3cr3t
  rabbitmq:
    host: localhost
    port: 5672
    username: accounting
    password: s3cr3t
    virtual-host: accounting
    dynamic: true
    listener:
      simple:
        acknowledge-mode: manual
